dis: bionic

language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install cassandra
install:
  - pip install -r requirements.txt
services:
  - cassandra
before_script:
- bash travis/setup_cassandra.sh
# command to run tests
script:
  - pytest