dis: bionic

language: python
python:
  - "3.7"
before_install:
  - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
  - sudo service cassandra start
  - sleep 3
install:
  - pip install -r requirements.txt
services:
  - cassandra
before_script:
- bash travis/setup_cassandra.sh
# command to run tests
script:
  - pytest