dis: bionic

language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://apachemirror.wuchna.com/cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz && tar -xvzf apache-cassandra-3.11.4-bin.tar.gz && sudo sh apache-cassandra-3.11.4/bin/cassandra
install:
  - pip install -r requirements.txt
services:
  - cassandra
before_script:
- bash travis/setup_cassandra.sh
# command to run tests
script:
  - pytest