dis: bionic

language: python
python:
  - "3.7"
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"$JVM_OPTS -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
install:
  - pip install -r requirements.txt
services:
  - cassandra
before_script:
- bash travis/setup_cassandra.sh
# command to run tests
script:
  - pytest