language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install cassandra
install:
  - pip install -r requirements.txt
services:
  - cassandra
before_script:
- bash travis/setup_cassandra.sh
# command to run tests
script:
  - pytest